- custom_components/polestar_api/translations/de.json
Started to add translations. Even though I am not sure it will be used like that in the future ;)
> Add german language

- custom_components/polestar_api/translations/sv.json
Adding Swedish with the help of my wife :smiley:
> Swedish translation

- custom_components/polestar_api/sensor.py
- custom_components/polestar_api/translations/de.json
> Correct German translations

- custom_components/polestar_api/sensor.py
I changed some of the sensor icons to better fit for purpose.
Side note: I accidentally added these changes to the PR for changing the German translation but reverted these changes back, sorry for that.
> Changed some sensor icons for better fit

- custom_components/polestar_api/translations/fr.json
Here's the french translations.
> French translations

- custom_components/polestar_api/translations/da.json
> Danish translation

- custom_components/polestar_api/translations/da.json
Used de.json as template:
- Updated translation to reflect updated entity names
- Sorted by entity name to support identifying missing translations
> Danish translation updated

- custom_components/polestar_api/sensor.py
> update average_speed to be a SPEED not DISTANCE

- custom_components/polestar_api/translations/ko.json
I've added translation json file for Korean.
It seems there are some changes on going, so I referenced **Danish** file since it seems to be the completed one.
Although, I couldn't test because it's not working properly in my setup.
I'll keep in watch for any updates :)
> Add Korean translation

- custom_components/polestar_api/pypolestar/polestar.py
Fix internal server error status never returning to OK.
> Change BASE_URL to BASE_URL_V2 to fix internal server error

- .github/workflows/validate.yml
- custom_components/polestar_api/manifest.json
- hacs.json
Ensure we have everything needed for inclusion in the list of default HACS integrations.
> Updates for inclusion in HACS

- custom_components/polestar_api/polestar.py
- custom_components/polestar_api/pypolestar/auth.py
- custom_components/polestar_api/pypolestar/polestar.py
> Use get_async_client

- custom_components/polestar_api/manifest.json
Set version number to 1.7.2 for next release
> prepare for release 1.7.2

- custom_components/polestar_api/manifest.json
Fixes problem with image entities
> prepare for release 1.7.3

- custom_components/polestar_api/__init__.py
- custom_components/polestar_api/image.py
- custom_components/polestar_api/polestar.py
- custom_components/polestar_api/sensor.py
Add some type notations and use a shared function to get the "unique" ID (which is actually not unique in cases where you happen to own two cars with the same last 4 digits in the VIN).
> Add some type notations and split out get_unique_id

- custom_components/polestar_api/__init__.py
Remove (what I believe is) unused code. WDYT @leeyuentuen ?
> Remove unused code

- custom_components/polestar_api/__init__.py
> use async_forward_entry_setups

- custom_components/polestar_api/pypolestar/auth.py
- custom_components/polestar_api/pypolestar/const.py
- custom_components/polestar_api/pypolestar/polestar.py
- Move static URLs to const
- Fetch endpoints via well-known OIDC configuration
> General OIDC improvements

- custom_components/polestar_api/__init__.py
- custom_components/polestar_api/entity.py
- custom_components/polestar_api/image.py
- custom_components/polestar_api/polestar.py
- custom_components/polestar_api/sensor.py
Clean up device init
Use VIN as device identifier (not name) as this never change
> Improve device init

- custom_components/polestar_api/config_flow.py
> Fix types and handle empty VIN

- custom_components/polestar_api/config_flow.py
- custom_components/polestar_api/pypolestar/polestar.py
We failed to fail early on login failure, do that.
> Fail early on login failure

- custom_components/polestar_api/pypolestar/auth.py
- custom_components/polestar_api/pypolestar/const.py
- custom_components/polestar_api/pypolestar/polestar.py
Refresh token 300 seconds before expire or half the lifetime if less than that
> Update token refresh logic

- custom_components/polestar_api/manifest.json
I believe we are in good shape to release 1.9.0 - it should at least work a lot better than 1.8.0. Please test and report back in this PR.
> Prepare for release 1.9.0

- custom_components/polestar_api/polestar.py
- custom_components/polestar_api/pypolestar/const.py
- custom_components/polestar_api/pypolestar/polestar.py
- custom_components/polestar_api/sensor.py
Clean up API status sensors removing v1/v2
> Remove API v1 and present APIs as "Auth" and "Data"
